/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectuas;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.SQLDataException;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

/**
 *
 * @author asus
 */
public class frmhs extends javax.swing.JFrame {
    private DefaultTableModel model;
    static ResultSet rs;
    static Statement stmt;    
    dbkoneksi cnn = new dbkoneksi();
    loadIMG img = new loadIMG();

    /**
     * Creates new form frmhs
     */
    public frmhs() {
        initComponents();
        this.initTable();
        this.getdata();
        this.tutup.setEnabled(true);
        this.navbar(false);
        this.batal.setVisible(false);
    }

    private void initTable(){
        model = new DefaultTableModel();
        tMHS.setModel(model);
        model.addColumn("NIM");
        model.addColumn("NAMA");
        model.addColumn("JURUSAN");
        model.addColumn("JENIS KELAMIN");
        model.addColumn("TGL LAHIR");
    }
    
    private void getdata(){
        String sql = "Select NIM, NAMA, JURUSAN, JENISKELAMIN, TGL_LHR FROM datamhs;";
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try{
            this.tampildata(sql);
            while(this.rs.next()){
                Object[] obj = new Object[5];
                obj[0] = this.rs.getString("NIM");
                obj[1] = this.rs.getString("NAMA");
                obj[2] = this.rs.getString("JURUSAN");
                obj[4] = this.rs.getString("TGL_LHR");
                String buttonGroup1 = this.rs.getString("JENISKELAMIN");
                if(buttonGroup1.equals("Laki - Laki")){
                    obj[3] = "Laki - Laki";
                }else{
                    obj[3] = "Perempuan";
                }
                model.addRow(obj);
            }
            stmt.close();
            cnn.koneksi().close();
            }catch(Exception e){
        }         
    }
    
    private void tampildata(String sql){
    try {
            Statement stmt = cnn.koneksi().createStatement();
            this.rs = stmt.executeQuery(sql);
        }catch(Exception e){
            System.out.println("SALAH");
        }
    }
    
    private boolean updatedata(String sql){
        boolean hsl = false;
        try{
            Statement stmt = cnn.koneksi().createStatement();
            stmt.executeUpdate(sql);
            hsl = true;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Terjadi kendala pada instruksi SQL");
        }
        return hsl;
    }
    
    private void simpandata(){
        String NIM = this.txtnim.getText();
        String NAMA = this.txtnama.getText();
        String JURUSAN = this.txjur.getSelectedItem().toString();
        String JENISKELAMIN = "Perempuan";
        if(this.txL.isSelected()){
        JENISKELAMIN = "Laki - Laki";
        }
        String TGL_LHR = this.tgllhr.getText();
        String sql = "INSERT INTO datamhs (NIM, NAMA, JURUSAN, JENISKELAMIN, TGL_LHR) VALUES ('"+NIM+"','"+NAMA+"', '"+JURUSAN+"', '"+JENISKELAMIN+"', '"+TGL_LHR+"');";
        if (this.updatedata(sql)){
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");
        }
        this.getdata();
        this.simpan.setEnabled(false);
        this.batal.setVisible(false);
    }
    
        private void updatedataform(){
        String NIM = this.txtnim.getText();
        String NAMA = this.txtnama.getText();
        String JURUSAN = this.txjur.getSelectedItem().toString();
        String TGL_LHR = this.tgllhr.getText();
        String JENISKELAMIN = "Perempuan";
            if(this.txL.isSelected()){
        JENISKELAMIN = "Laki - Laki";
        }
        String sql = "UPDATE datamhs SET NIM= '"+NIM+"', NAMA= '"+NAMA+"', JURUSAN= '"+JURUSAN+"', JENISKELAMIN= '"+JENISKELAMIN+"', TGL_LHR='"+TGL_LHR+"');";
        if (this.updatedata(sql)){
            JOptionPane.showMessageDialog(null, "Data Mahasiswa"+NAMA+" telah diupdate");
        }
        this.getdata();
        this.simpan.setEnabled(false);
        this.batal.setVisible(false);
    }
        
    private void navbar(Boolean tf){
        this.simpan.setEnabled(tf);
        this.update.setEnabled(tf);
        this.hapus.setEnabled(tf);
        this.tutup.setEnabled(tf);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tMHS = new javax.swing.JTable();
        databaru = new javax.swing.JButton();
        txL = new javax.swing.JRadioButton();
        txP = new javax.swing.JRadioButton();
        tgllhr = new javax.swing.JTextField();
        lbtgllhr = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tutup = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        update = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        imgphoto = new javax.swing.JLabel();
        txtnim = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txjur = new javax.swing.JComboBox<>();
        lbjur = new javax.swing.JLabel();
        lbnama = new javax.swing.JLabel();
        lbnim = new javax.swing.JLabel();
        lbeditdata = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DATA MAHASISWA");
        jLabel1.setToolTipText("");

        tMHS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Jurusan", "Jenis Kelamin", "Tgl Lahir"
            }
        ));
        tMHS.setName(""); // NOI18N
        tMHS.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tMHSAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                tMHSAncestorRemoved(evt);
            }
        });
        tMHS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tMHSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tMHS);

        databaru.setText("Data Baru");
        databaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databaruActionPerformed(evt);
            }
        });

        buttonGroup1.add(txL);
        txL.setText("Laki - Laki");
        txL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txLActionPerformed(evt);
            }
        });

        buttonGroup1.add(txP);
        txP.setText("Perempuan");

        lbtgllhr.setText("Tanggal Lahir");

        jLabel5.setText("Jenis Kelamin");

        tutup.setText("Tutup Data Mahasiswa");
        tutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutupActionPerformed(evt);
            }
        });

        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        hapus.setText("Hapus Data");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        update.setText("Update Data");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        simpan.setText("Simpan Data");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        imgphoto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        imgphoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgphoto.setText("FOTO");
        imgphoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txjur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TI - KAB", "TI - DGM", "TI - MTI", "SK" }));

        lbjur.setText("Jurusan");

        lbnama.setText("Nama");

        lbnim.setText("NIM");

        lbeditdata.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbeditdata.setText("EDIT DATA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(databaru))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(update)
                        .addGap(18, 18, 18)
                        .addComponent(hapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(batal)
                        .addGap(18, 18, 18)
                        .addComponent(tutup))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imgphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbnama)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbjur)
                                            .addComponent(lbnim))
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txjur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtnama)
                                            .addComponent(txtnim, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txP)
                                            .addComponent(txL)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbtgllhr)
                                        .addGap(18, 18, 18)
                                        .addComponent(tgllhr, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lbeditdata))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(databaru))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lbeditdata)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(imgphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbnama))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbtgllhr)
                                    .addComponent(tgllhr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txP)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbnim))
                            .addGap(18, 18, 18)
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txjur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbjur)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan)
                    .addComponent(update)
                    .addComponent(hapus)
                    .addComponent(tutup)
                    .addComponent(batal))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tMHSAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tMHSAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tMHSAncestorAdded

    private void tMHSAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tMHSAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tMHSAncestorRemoved

    private void tMHSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tMHSMouseClicked
        //String urlGambarNull = "src/img/gambar.jpg";
        this.txtnim.setText( model.getValueAt(tMHS.getSelectedRow(), 0).toString());
        this.txtnama.setText( model.getValueAt(tMHS.getSelectedRow(), 1).toString());
        this.txjur.setSelectedItem(model.getValueAt(tMHS.getSelectedRow(), 2).toString());
        this.tgllhr.setText( model.getValueAt(tMHS.getSelectedRow(), 4).toString());
        String buttonGroup1 = model.getValueAt(tMHS.getSelectedRow(), 3).toString();
        if(buttonGroup1.equals("Perempuan")){
            this.txP.setSelected(true);
        }else{
            this.txL.setSelected(true);
        }
        /*String urlGambar = "src/img/"+this.txtnim.getText() + ".jpg";
        BufferedImage loadImg = img.loadImage(urlGambar);
        if(loadImg == null){
            loadImg = img.loadImage(urlGambarNull);
        }
        ImageIcon imageIcon = new ImageIcon(loadImg);
        */
        this.lbeditdata.setText("Edit Data "+this.txtnim.getText());
        this.simpan.setEnabled(false);
        this.update.setEnabled(true);
        this.hapus.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_tMHSMouseClicked

    private void databaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databaruActionPerformed
        this.databaru.setEnabled(false);
        this.update.setEnabled(false);
        this.hapus.setEnabled(false);
        this.tutup.setEnabled(false);
        this.simpan.setEnabled(true);
        this.batal.setVisible(true);

        this.txtnim.setText("");
        this.txtnama.setText("");
        this.tgllhr.setText("");
        this.txjur.setSelectedIndex(0);
        this.lbeditdata.setText("Tambah data Mahasiswa");
        // TODO add your handling code here:
    }//GEN-LAST:event_databaruActionPerformed

    private void txLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txLActionPerformed

    private void tutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutupActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_tutupActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        this.tutup.setEnabled(true);
        this.databaru.setEnabled(true);
        this.simpan.setEnabled(false);
        this.batal.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_batalActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        String NIM = this.txtnim.getText();
        String NAMA = this.txtnama.getText();

        int opsi = JOptionPane.showConfirmDialog(null,"Yakin akan menghapus data dari "+NAMA+"("+NIM+")?","Konfirmasi", JOptionPane.YES_NO_OPTION );
        if(opsi == JOptionPane.YES_OPTION){
            String sqlDelete = "DELETE FROM datamhs WHERE NIM='"+NIM+"';";
            if(this.updatedata(sqlDelete)){
                this.getdata();
                JOptionPane.showMessageDialog(null, "Data telah dihapus");
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_hapusActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String NIM = this.txtnim.getText();
        String NAMA = this.txtnama.getText();
        String JURUSAN = this.txjur.getSelectedItem().toString();
        String TGL_LHR = this.tgllhr.getText();
        String JENISKELAMIN = "Laki - Laki";
        if(this.txP.isSelected()){
            JENISKELAMIN = "Perempuan";
        }
        String sqlUpdate = "UPDATE datamhs SET NAMA='"+NAMA+"', JURUSAN='"+JURUSAN+"', JENISKELAMIN='"+JENISKELAMIN+"', TGL_LHR='"+TGL_LHR+"' WHERE NIM='"+NIM+"';";
        if(this.updatedata(sqlUpdate)){
            this.getdata();
            JOptionPane.showMessageDialog(null, "Data telah di Update");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        String NIM = this.txtnim.getText();
        String NAMA = this.txtnama.getText();
        String JURUSAN = this.txjur.getSelectedItem().toString();
        String TGL_LHR = this.tgllhr.getText();
        String JENISKELAMIN = "Laki - Laki";
        if(this.txP.isSelected()){
            JENISKELAMIN = "Perempuan";
        }
        String sqlInsert = "INSERT INTO datamhs (NIM, NAMA, JURUSAN, JENISKELAMIN, TGL_LHR) VALUES ('"+NIM+"','"+NAMA+"', '"+JURUSAN+"', '"+JENISKELAMIN+"', '"+TGL_LHR+"');";
        if(this.updatedata(sqlInsert)){
            this.getdata();
            JOptionPane.showMessageDialog(null, "Data telah di Tambahkan");
        }
        this.simpan.setEnabled(false);
        this.batal.setVisible(false);
        this.tutup.setEnabled(true);
        this.databaru.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_simpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmhs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton databaru;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel imgphoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbeditdata;
    private javax.swing.JLabel lbjur;
    private javax.swing.JLabel lbnama;
    private javax.swing.JLabel lbnim;
    private javax.swing.JLabel lbtgllhr;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tMHS;
    private javax.swing.JTextField tgllhr;
    private javax.swing.JButton tutup;
    private javax.swing.JRadioButton txL;
    private javax.swing.JRadioButton txP;
    private javax.swing.JComboBox<String> txjur;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnim;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
